// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy97UkVU3cnDL-mQDSEGoCaAn290K0gNQ',
    appId: '1:148402985937:web:586381051b5b85c856def0',
    messagingSenderId: '148402985937',
    projectId: 'cmsc-23-project-7ad82',
    authDomain: 'cmsc-23-project-7ad82.firebaseapp.com',
    storageBucket: 'cmsc-23-project-7ad82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgDnRr0USYvB4ujDtxXtcfKcXRB3ev50',
    appId: '1:148402985937:android:9dd9ccde923b0f6856def0',
    messagingSenderId: '148402985937',
    projectId: 'cmsc-23-project-7ad82',
    storageBucket: 'cmsc-23-project-7ad82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-R-k_EM8d2O7rCu2b7o4r6brAeyZqNo',
    appId: '1:148402985937:ios:80974f2758d5d67a56def0',
    messagingSenderId: '148402985937',
    projectId: 'cmsc-23-project-7ad82',
    storageBucket: 'cmsc-23-project-7ad82.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-R-k_EM8d2O7rCu2b7o4r6brAeyZqNo',
    appId: '1:148402985937:ios:80974f2758d5d67a56def0',
    messagingSenderId: '148402985937',
    projectId: 'cmsc-23-project-7ad82',
    storageBucket: 'cmsc-23-project-7ad82.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy97UkVU3cnDL-mQDSEGoCaAn290K0gNQ',
    appId: '1:148402985937:web:39b76daf39629c0e56def0',
    messagingSenderId: '148402985937',
    projectId: 'cmsc-23-project-7ad82',
    authDomain: 'cmsc-23-project-7ad82.firebaseapp.com',
    storageBucket: 'cmsc-23-project-7ad82.appspot.com',
  );
}
